Create Make.mach.nasa-aitken-rome
enzo-project/enzo-dev pull request #173
Opened 2021-06-03 18:50 UTC by peeples

Makefile for NASA's Aitken Rome nodes

2021-06-03 18:58 UTC, peeples commented
Added my various commits to updating the regular Pleiades file while I was at it

2021-08-10 22:00 UTC, jwise77 approved these changes

2021-08-12 09:41 UTC, pgrete requested changes
I suggest to add architecture specific optimization flags and remove the explicit reference to the python libs.

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-aitken-rome
> +MACH_OPT_AGGRESSIVE  = -O3  -ip -ipo
```suggestion
# Best for Aitken Rome nodes
# See: https://www.nas.nasa.gov/hecc/support/kb/preparing-to-run-on-aitken-rome-nodes_657.html
MACH_OPT_HIGH        = -g -O2  -ip -ipo -march=core-avx2
MACH_OPT_AGGRESSIVE  = -O3  -ip -ipo -march=core-avx2
```

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-aitken-rome
> +                        -I$(LOCAL_PYTHON_INSTALL)/lib/python2.7/site-packages/numpy/core/include
Python 2 is now EOL and this variable not processed further so I suggest to remove it.
```suggestion
```

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-aitken-rome
> +#LOCAL_LIBS_PYTHON  = $(LOCAL_PYTHON_INSTALL)/lib/python2.6/config/libpython2.6.a -lpthread -lutil
As above 
```suggestion
```

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-aitken-rome
> +MACH_LIBS         = $(LOCAL_LIBS_HDF5) $(LOCAL_LIBS_MACH) $(LOCAL_LIBS_GRACKLE) #$(LOCAL_LIBS_PYTHON)
As above
```suggestion
MACH_LIBS         = $(LOCAL_LIBS_HDF5) $(LOCAL_LIBS_MACH) $(LOCAL_LIBS_GRACKLE)
```

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-pleiades
>  MACH_OPT_AGGRESSIVE  = -O3 -xAVX -ip -ipo
```suggestion
MACH_OPT_HIGH        = -g -O2 -axCORE-AVX512,CORE-AVX2 -xAVX -ip -ipo
MACH_OPT_AGGRESSIVE  = -O3 -axCORE-AVX512,CORE-AVX2 -xAVX -ip -ipo
```

2021-08-12 09:41 UTC, pgrete commented on src/enzo/Make.mach.nasa-pleiades
> +# Best for pleiades ivy bridge, haswell, and broadwell nodes.
```suggestion
# Best for pleiades ivy bridge, haswell, broadwell, skylake and cascade lake nodes.
```

2022-07-13 15:13 UTC, jwise77 commented
@peeples I fixed the testing in #190, and I merged in these changes to run the test suite on this PR. But I couldn't push the tags to your PR. Could you issue the command `git fetch https://github.com/jwise77/enzo-dev --tags` to bring in the new gold-standard-v15 tag for testing?

@pgrete I incorporated your recommended changes to the machine file. Could you approve?

Thanks!

2022-07-14 09:26 UTC, pgrete commented
It looks like this PR is now mixed with changes from #190 so #190 should go in first to cleanup this PR.

2022-07-15 08:20 UTC, pgrete approved these changes
LGTM

2022-07-15 10:51 UTC, merged