Updated ionizing photon rates from rotating (and non-rotating) Pop III Stars
enzo-project/enzo-dev pull request #195
Opened 2022-07-25 13:36 UTC by drenniks

This model comes from [Murphy et al. 2021](https://arxiv.org/abs/2105.06900). Implemented within Enzo are new ionizing photon rates for H, HeI, and HeII for non-rotating and rotating Pop III stars (see their Figure 2). 

A parabola is fit to these ionization rates up to 80% of the star's life. After that point, the ionizing photon rate is assumed to be constant. The coefficients of the fit are accurate down to 1% of the standard error. 

Pop III stars only within the mass range of 9 <= M / Msun <= 120 are affected by this new model. 

A new parameter has been added: 
- Rotating_PopIII controls whether the stars are rotating or non-rotating. 
- Rotating_PopIII = 0 : non-rotating -- this is default
- Rotating_PopIII = 1 : rotating

2022-07-25 13:54 UTC, jwise77 requested changes
All looks good so far! Because you're adding a new parameter, you need to add this to the documentation.

2022-07-25 13:54 UTC, jwise77 commented on src/enzo/Grid_TestRadiatingStarParticleInitializeGrid.C
> +           float PhotonTestInitialFractionHII,
Change all of the `PhotonTest` variables to start with `TestStarParticle` to be consistent with other parameters.

2022-07-25 13:54 UTC, jwise77 commented on run/StarParticle/RadiatingStarParticleSingleTest/TestRadiatingStarParticleSingle.enzo
> +StarParticleFeedback   = 16384 // Population III Stars
Isn't this feedback method 14 (kinetic feedback), not Pop III?

2022-07-25 13:54 UTC, jwise77 commented on src/enzo/Grid.h
> +               float PhotonTestInitialFractionHII,
Change all of the `PhotonTest` variables to start with `TestStarParticle` to be consistent with other parameters.

2022-07-25 13:54 UTC, jwise77 commented on src/enzo/Make.mach.linux-gnu
> +LOCAL_HDF5_INSTALL    = /home/dskinner6/software/yt-conda/pkgs/hdf5-1.10.2-hc401514_3# mandatory
Revert this changes to exclude your directories. You can put a copy of your machine file in `~/.enzo/` that overrides any machine files in the enzo/ directory.

2022-07-25 13:54 UTC, jwise77 commented on src/enzo/Star_ComputePhotonRates.C
> +      if (PopIII_Rotating == 1) {
For some set of parameters, we should leave in the Schaerer (2002) photon luminosities to give a consistent model with the other mass ranges and to reproduce previous simulations. Here we're replacing them with the new non-rotational models.

2022-07-25 13:54 UTC, jwise77 commented on src/enzo/TestRadiatingStarParticleInitialize.C
> +             PhotonTestInitialTemperature,
Use the `TestProblemData` variables instead of the `PhotonTest` ones.

2022-08-01 20:28 UTC, jwise77 approved these changes

2022-08-01 20:32 UTC, jwise77 commented
Hi @gregbryan, this PR expands on your TestStarParticle problem to make the particle a radiating Pop III star that uses the same machinery as cosmological simulations. I hope you have the time to review these changes! If not, just let us know. Thanks!

2022-08-02 13:21 UTC, gregbryan commented on src/enzo/Star_ComputePhotonRates.C
> +    _age = this->ReturnAge()/this->LifeTime; //Percentage of lifetime
The indentation here makes this looks like _age is part of the else block, but there are no brackets ({}), so it is not. Maybe fix indentation to make it clear?

2022-08-02 13:26 UTC, gregbryan commented on src/enzo/Grid_FindNewStarParticles.C
> +	  if (PopIIIInitialMassFunction == FALSE){
Very minor point, but it would be nice if you could add all the brackets (i.e. {}) to this set of if statements (and clean up indentation).

2023-05-04 12:48 UTC, bwoshea commented
@drenniks can you take a quick look at this PR?  Specifically, would you be willing to address @gregbryan 's comments?  They're relatively minor, but would help clean things up a bit.  If you can do that we can merge the PR.

2023-05-15 16:45 UTC, drenniks commented on src/enzo/PopIIIRotationModel.C
> +    if (find_element(Mass, (float*)mass_list, nentries) != -1) {
I see what you are saying, I think I will leave this as is. The linear interpolation is going to be used the majority of the time anyway, I'm thinking. But thanks for pointing this out!

2023-05-15 16:49 UTC, drenniks commented
> @drenniks can you take a quick look at this PR? Specifically, would you be willing to address @gregbryan 's comments? They're relatively minor, but would help clean things up a bit. If you can do that we can merge the PR.

Apologies for the long delay on this! Just addressed and pushed the changes.

2023-05-15 23:01 UTC, merged